### ISSUE TITLE
Please update Bento on cocoapods to 0.3

### ISSUE THREAD

**Issue by jtomanik** [Babylonpartners/Bento#124]
Currently, the version available on cocoapods is 0.2 https://cocoapods.org/pods/Bento .
Therefore doing `pod 'Bento'` on Xcode 10 results in a broken build.
Could you please update version available through official cocoapods channel to the newest?

**Comment by TheAdamBorek** [comment]
done :) 

We're planning to release 0.4.0 soon :)
