### ISSUE TITLE
Why the separation between Bento / BentoKit / StyleSheets?

### ISSUE THREAD

**Issue by mluisbrown** [Babylonpartners/Bento#144]
## Why the separation between Bento / BentoKit / StyleSheets?

Is anyone realistically going to use `Bento` on its own? I don’t really think so, because it has no ready to use components, so only a masochist would go down that route. However, `BentoKit`, which gives you some components, obliges you to integrate ReactiveSwift/ReactiveCocoa (RAS/RAC) into your project, even if you don’t want to use it.

None of the `Component`s in `BentoKit` require RAS/RAC except `TitledDescription` 🤦‍♂️, which only uses it for the `image` property.

In fact, the *only* things in `BentoKit` that require RAS/RAC are: `BoxViewModel`, `BoxViewController` and `ImageOrLabelView` (and therefore `TitledDescription`). For `ImageOrLabelView` it’s only a `Reactive` extension which could easily be moved elsewhere.

`StyleSheets` is also required to use the `Component`s so TBH I don’t see why it needs to be in a separate framework (it’s not particularly useful on its own)

If we want `Bento` to be developer friendly ideally we should:

- move all the `Component`s from `BentoKit` into `Bento` (except `TitledDescription`) 
- move what remains of `BentoKit` such as all the RAS/RAC things like `BoxViewModel`, `BoxViewController` and all that they are part of (`Screen` etc) into a new library into a separate repo.

That way in `Bento` we would be left with a nice declarative, component based, tableview / collection view library (`Bento` + components + `StyleSheets`) that anyone could use without being wedded to RAS/RAC or the `Screen` / `BoxViewController` / `BoxViewModel` architecture. 

`BentoKit` would become its own thing that depends on `Bento`.

**Comment by TheAdamBorek** [comment]
I like the idea of:
> That way in Bento we would be left with a nice declarative, component based, tableview / collection view library (Bento + components + StyleSheets) that anyone could use without being wedded to RAS/RAC or the Screen / BoxViewController / BoxViewModel architecture.

The only thing I keep thinking is if we should do this now if we're planning to introduce atomic components. Maybe it's better to hold until atomic components are part of bento and don't merge BentoKit?

**Comment by mluisbrown** [comment]
@TheAdamBorek I think we should do it now. If we keep waiting for "the next big thing" we will never do anything.

**Comment by TheAdamBorek** [comment]
yes, you are right. We don't release too often :/

**Comment by TheAdamBorek** [comment]
So... the final question is. Are we going to include this in 0.4.0?
My vote is: `yes` but we would need to have non-RAC version of TiteldDescription as we need at least one sample.

@mluisbrown have you started working on it?

**Comment by mluisbrown** [comment]
My vote is also `yes` to include this in `0.4.0`.

@TheAdamBorek I haven't started working on it yet 😞 But I think I should have time to start this week...

**Comment by TheAdamBorek** [comment]
Adding a milestone than.
As you haven't started it will give some time to others to veto ;)

**Comment by TheAdamBorek** [comment]
Im closing this issue as it's merged AFAIK
