### ISSUE TITLE
TitledDescription does not Respect number of line when calculating height

### ISSUE THREAD

**Issue by sergdort** [Babylonpartners/Bento#82]
If you take a look on the screenshot, There are two labels, one of which has limit to 2lines, but component does not takes this into account when it calculates the height

![screenshot 2018-11-23 at 15 25 10](https://user-images.githubusercontent.com/4622322/48950743-1b4a6b80-ef34-11e8-9047-0f7de8055812.png)

**Comment by andersio** [comment]
#83 has fixed this.
