### ISSUE TITLE
Configuring table view appearance

### ISSUE THREAD

**Issue by ilyapuchka** [Babylonpartners/Bento#84]
Currently there seem to be no way to change table view appearance, i.e. its background colour, managed by Bento as it is being set to `.clear` in `viewDidLoad` in `BoxViewController`. At the same time there is a `TableViewStyleSheet` that seem to be only used when table is part of some other Bento component.

I'd suggest to make it part of `Screen` API and apply it internally instead of setting hardcoded default as it is done right now (in [`private func configureTableView(_ tableView: UITableView) -> UITableView`](https://github.com/Babylonpartners/Bento/blob/e99609df31d0587b6e1bd41042e5a23a8a429060/BentoKit/BentoKit/Screen/BoxViewController.swift#L201)). i.e.: 

```
Screen(title: "", box: ..., style: TableViewStyleSheet(...))
```

Same can apply to the pinned boxes as they are implemented as separate table views, but usually contain just one component so things like background colour can be set through this component.

**Comment by andersio** [comment]
We are planning to replace `UITableView` in BoxVC. You may also achieve the same thing by implementing a `BoxRenderer.styleSheet` in general.
